-- 1.2.8


-- 1.2.7
WITH BEST_YEAR AS (
	SELECT DISTINCT EXTRACT(YEAR FROM HIRE_DATE) AS HIRE_YEAR, COUNT(EMPLOYEE_ID) AS EMPLOYEES_COUNT
	FROM EMPLOYEES

	GROUP BY EXTRACT(YEAR FROM HIRE_DATE)

	ORDER BY COUNT(EMPLOYEE_ID) DESC

	LIMIT 1
)

SELECT HIRE_YEAR
FROM BEST_YEAR;



-- 1.2.6
SELECT DISTINCT JOB_TITLE, COUNTRY_NAME
FROM EMPLOYEES

JOIN JOBS USING(JOB_ID)
JOIN DEPARTMENTS USING(DEPARTMENT_ID)
JOIN LOCATIONS USING(LOCATION_ID)
JOIN COUNTRIES USING(COUNTRY_ID)
JOIN REGIONS USING(REGION_ID)

WHERE REGION_NAME = 'Europe';



-- 1.2.5
SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES

JOIN DEPARTMENTS USING(DEPARTMENT_ID)
JOIN LOCATIONS USING(LOCATION_ID)
JOIN COUNTRIES USING(COUNTRY_ID)
JOIN REGIONS USING(REGION_ID)

WHERE REGION_NAME = 'Europe';



-- 1.2.4
SELECT COUNT(EMPLOYEE_ID) AS EMPLOYEES_FROM_EUROPE
FROM EMPLOYEES

JOIN DEPARTMENTS USING(DEPARTMENT_ID)
JOIN LOCATIONS USING(LOCATION_ID)
JOIN COUNTRIES USING(COUNTRY_ID)
JOIN REGIONS USING(REGION_ID)

WHERE REGION_NAME = 'Europe';



-- 1.2.3
SELECT COUNTRY_NAME, SUM(SALARY) AS SUM_SALARY
FROM EMPLOYEES e

JOIN DEPARTMENTS d ON(e.DEPARTMENT_ID = d.DEPARTMENT_ID)
JOIN LOCATIONS l ON(d.LOCATION_ID = l.LOCATION_ID)
JOIN COUNTRIES USING(COUNTRY_ID)

GROUP BY COUNTRY_ID, COUNTRY_NAME

ORDER BY SUM(SALARY) DESC, COUNTRY_ID;



-- 1.2.2
WITH EMPLOYEES_FROM_CANADA AS (
	SELECT (LAST_NAME || ' ' || FIRST_NAME) AS EMPLOYEE, SALARY, MANAGER_ID
	FROM EMPLOYEES
	
	JOIN (
		SELECT DEPARTMENT_ID, LOCATION_ID
		FROM DEPARTMENTS
	) USING(DEPARTMENT_ID)
	
	JOIN (
		SELECT LOCATION_ID, COUNTRY_ID
		FROM LOCATIONS
	) USING(LOCATION_ID)
	
	WHERE COUNTRY_ID = 'CA'
)

SELECT EMPLOYEES_FROM_CANADA.EMPLOYEE,
       EMPLOYEES_FROM_CANADA.SALARY,
       (EMPLOYEES.LAST_NAME || ' ' || EMPLOYEES.FIRST_NAME) AS MANAGER,
       EMPLOYEES.SALARY
FROM EMPLOYEES_FROM_CANADA

JOIN EMPLOYEES ON(EMPLOYEES_FROM_CANADA.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID)

ORDER BY EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME;


-- 1.2.1
SELECT SUM(SALARY) FROM EMPLOYEES

JOIN DEPARTMENTS USING(DEPARTMENT_ID)
JOIN LOCATIONS   USING(LOCATION_ID)

WHERE COUNTRY_ID = 'UK';
